#!/bin/sh

PNAME=euleR
LIBVER=1.0.0

LIBNAME=K-ttelbr-cke
LIBVER=1.0.0-SNAPSHOT

echo "Compiling Java sources ..."
(cd src-java; mvn package; cd ..)

echo "$PNAME version ${VER}"

echo "Creating package ..."
mkdir inst
cp src-java/target/${LIBNAME}-${LIBVER}.jar inst/
echo "Done."
